server:
  port: 7005
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elasticsearch_sync
    username: root
    password: root123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update